--1. CREATE A TABLESPACE MID_TERM WITH ONE DATAFILE OF 50Mb (For the datafile don't put the path, just the name of the datafile)

CREATE  TABLESPACE MID_TERM
DATAFILE 'MID_TERM.dbf' SIZE 50M;

--2. CREATE AN USER WITH 20Mb ASSIGNED TO THE TABLESPACE MID_TERM
CREATE USER usua
    IDENTIFIED BY usua 
    DEFAULT TABLESPACE MID_TERM
    QUOTA 20M ON example;
alter user usua QUOTA 20M ON MID_TERM;
       
--3. GIVE THE DBA ROLE TO THE USER, ALSO SHOULD BE ABLE TO LOG IN.     

GRANT CONNECT TO usua;

ALTER USER usua PROFILE student;

GRANT CREATE ON DBA TO usua;
create role DBA;
--asignar rol al usuario
grant DBA to usua;
connect usua;
4. CREATE TWO SEQUENCES:
	--5.1 COMUNAS_SEQ SHOULD START IN 50 WITH INCREMENTS OF 3
	--5.2 COLEGIOS_SEQ SHOULD START IN 100 WITH INCREMENTS OF 1
    
    --1
    CREATE SEQUENCE COMUNAS_SEQ
    START WITH 50 INCREMENT BY 3  NOCYCLE;
        -
    CREATE SEQUENCE COLEGIOS_SEQ
    START WITH 100 INCREMENT BY 1  NOCYCLE;

--5. CREATE THE NEXT TABLES:

CREATE TABLE COMUNAS (
	ID INTEGER PRIMARY KEY,
	NOMBRE VARCHAR2(255)
)
INSERT INTO COMUNAS VALUES (1,	'POPULAR');
INSERT INTO COMUNAS VALUES (10,	'LA CANDELARIA');
INSERT INTO COMUNAS VALUES (11,	'LAURELES ESTADIO');
INSERT INTO COMUNAS VALUES (12,	'LA AMERICA');
INSERT INTO COMUNAS VALUES (13,	'SAN JAVIER');
INSERT INTO COMUNAS VALUES (14,	'POBLADO');
INSERT INTO COMUNAS VALUES (15,	'GUAYABAL');
INSERT INTO COMUNAS VALUES (16,	'BELÉN');
INSERT INTO COMUNAS VALUES (2,	'SANTA CRUZ');
INSERT INTO COMUNAS VALUES (3,	'MANRIQUE');
INSERT INTO COMUNAS VALUES (4,	'ARANJUEZ');
INSERT INTO COMUNAS VALUES (5,	'CASTILLA');
INSERT INTO COMUNAS VALUES (50,	'PALMITAS');
INSERT INTO COMUNAS VALUES (6,	'DOCE DE OCTUBRE');
INSERT INTO COMUNAS VALUES (60,	'SAN CRISTOBAL');
INSERT INTO COMUNAS VALUES (7,	'ROBLEDO');
INSERT INTO COMUNAS VALUES (70,	'ALTAVISTA');
INSERT INTO COMUNAS VALUES (8,	'VILLA HERMOSA');
INSERT INTO COMUNAS VALUES (80,	'SAN ANTONIO DE PRADO');
INSERT INTO COMUNAS VALUES (9,	'BUENOS AIRES');
INSERT INTO COMUNAS VALUES (90,	'SANTA ELENA');

DROP TABLE COLEGIOS
create table colegios (
	ID INTEGER PRIMARY KEY,
	consecutivo_dane VARCHAR2(255),
	nombre_sede VARCHAR2(255),
	tipo_sede VARCHAR2(255),
	comuna_id INTEGER,
	prestacion_servicio VARCHAR2(255),
	zona VARCHAR2(255),
	barrio VARCHAR2(255),
	sector VARCHAR2(255),
	direccion_sede VARCHAR2(255),
	telefono_sede VARCHAR2(255),
	rector VARCHAR2(255),
	contador_prejardin_jardin INTEGER,
	contador_transicion INTEGER,
	contador_primaria INTEGER,
	contador_secundaria INTEGER,
	contador_media INTEGER,
	contador_adultos INTEGER,
	jornada_completa VARCHAR(8),
	jornada_manana VARCHAR(8),
	jornada_tarde VARCHAR(8),
	jornada_nocturna VARCHAR(8),
	jornada_fin_de_semana VARCHAR(8),
	jornada_unica VARCHAR(8),
	clasificacion_icfes VARCHAR(8),
    CONSTRAINT COMUNA_FK
    FOREIGN KEY (comuna_id)
    REFERENCES COMUNAS (id)
);
SELECT  M.ID, m.nombre_sede,m.comuna_id,  m.nombre as NOMBRE_COMUNA, m.contador_secundaria AS CONTADOR_SECUNDARIA, 
        round(AVG(b.contador_secundaria) OVER (PARTITION BY a.nombre),2)  AS PROMEDIO_SECUNDARIA_COMUNA
FROM COMUNAS A
INNER JOIN COLEGIOS B
ON A.id = b.comuna_id
WHERE b.prestacion_servicio = 'NO OFICIAL'
AND contador_prejardin_jardin > 0
AND a.nombre IN ('ARANJUEZ', 'CASTILLA','DOCE DE OCTUBRE');